# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Dinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Dinder
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

  target 'DinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DinderUITests' do
    # Pods for testing
  end

end
